# Generated by Django 6.0 on 2026-01-04 06:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=50, unique=True)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('current_living_location', models.CharField(max_length=255)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GaitProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gait_data', models.JSONField(help_text='Stored gait features or raw signal references')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gait_profile', to='monitoring.person')),
            ],
        ),
        migrations.CreateModel(
            name='CrossingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_identified', models.BooleanField(default=False)),
                ('raw_gait_data', models.JSONField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crossings', to='monitoring.person')),
            ],
        ),
    ]
